# TemplateCIConfig { bench: BenchEntry(MatrixEntry { run: false, run_cron: false, version: "nightly", install_commandline: None, commandline: "cargo bench" }), clippy: ClippyEntry(MatrixEntry { run: true, run_cron: false, version: "stable", install_commandline: Some("rustup component add clippy"), commandline: "cargo clippy -- -D warnings" }), rustfmt: RustfmtEntry(MatrixEntry { run: true, run_cron: false, version: "stable", install_commandline: Some("rustup component add rustfmt"), commandline: "cargo fmt -v -- --check" }), additional_matrix_entries: {"generated_files": CustomEntry(MatrixEntry { run: true, run_cron: false, version: "stable", install_commandline: Some("apt-get update -q && apt-get -qy install git && make names && git add ."), commandline: "env PAGER=cat git diff --cached && git diff-index --cached --exit-code HEAD" }), "unicode_version": CustomEntry(MatrixEntry { run: true, run_cron: true, version: "stable", install_commandline: Some("apt-get update -q && apt-get -qy install git && make fetch && git add ."), commandline: "env PAGER=cat git diff --cached && git diff-index --cached --exit-code HEAD" })}, cache: "cargo", os: "linux", dist: "xenial", versions: ["stable", "nightly"], test_commandline: "cargo test --verbose --all", scheduled_test_branches: ["master"], test_schedule: "0 0 * * 0" }
version: "2.1"

executors:
  stable:
    docker:
      - image: liuchong/rustup:stable
  nightly:
    docker:
      - image: liuchong/rustup:nightly
  beta:
    docker:
      - image: liuchong/rustup:beta

commands:
  cargo_test:
    description: "Run `cargo test`"
    steps:
      - run:
          name: "Clean out rust-toolchain"
          command: "rm -f rust-toolchain"
      - run:
          name: "Toolchain debug info"
          command: "rustc --version"
      - run:
          name: Test
          command: cargo test --verbose --all

jobs:
  test:
    parameters:
      version:
        type: executor
      version_name:
        type: string
    executor: << parameters.version >>
    environment:
      CI_RUST_VERSION: << parameters.version_name >>
    steps:
      - checkout
      - cargo_test

  rustfmt:
    parameters:
      version:
        type: executor
    executor: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add rustfmt
      - run:
          name: Rustfmt
          command: cargo fmt -v -- --check

  clippy:
    parameters:
      version:
        type: executor
    executor: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Install
          command: rustup component add clippy
      - run:
          name: Clippy
          command: cargo clippy -- -D warnings

  bench:
    parameters:
      version:
        type: executor
    executor: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Bench
          command: cargo bench
  generated_files:
    parameters:
      version:
        type: executor
      version_name:
        type: string
    executor: << parameters.version >>
    environment:
      CI_RUST_VERSION: << parameters.version_name >>
    steps:
      - checkout
      - run:
          name: Install
          command: apt-get update -q && apt-get -qy install git && make names && git add .
      - run:
          name: env PAGER=cat git diff --cached && git diff-index --cached --exit-code HEAD
          command: env PAGER=cat git diff --cached && git diff-index --cached --exit-code HEAD
  unicode_version:
    parameters:
      version:
        type: executor
      version_name:
        type: string
    executor: << parameters.version >>
    environment:
      CI_RUST_VERSION: << parameters.version_name >>
    steps:
      - checkout
      - run:
          name: Install
          command: apt-get update -q && apt-get -qy install git && make fetch && git add .
      - run:
          name: env PAGER=cat git diff --cached && git diff-index --cached --exit-code HEAD
          command: env PAGER=cat git diff --cached && git diff-index --cached --exit-code HEAD

  ci_success:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Success
          command: "echo yay"

workflows:
  continuous_integration:
    jobs:
      - test:
          name: test-stable
          version: stable
          version_name: stable
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - test:
          name: test-nightly
          version: nightly
          version_name: nightly
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - rustfmt:
          version: stable
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - clippy:
          version: stable
          filters: {
  "branches": {
    "ignore": [
      "/.*\\.tmp/"
    ]
  },
  "tags": {
    "only": [
      "/^v\\d+\\.\\d+\\.\\d+.*$/"
    ]
  }
}
      - generated_files:
          name: "generated_files"
          version: stable
          version_name: stable
      - unicode_version:
          name: "unicode_version"
          version: stable
          version_name: stable
      - ci_success:
          requires:
          - test-stable
          - test-nightly
          - rustfmt
          - clippy
          - generated_files
          - unicode_version
  scheduled_tests:
    jobs:
      - test:
          name: test-stable
          version: stable
          version_name: stable
      - test:
          name: test-nightly
          version: nightly
          version_name: nightly
      - unicode_version:
          name: "unicode_version"
          version: "stable"
          version_name: "stable"
    triggers:
      - schedule:
          cron: 0 0 * * 0
          filters:
            branches:
              only: [
  "master"
]
